planner_frequency: 0.2

file_path: /home/srikaanth/harvtech_ws/src/navigation/csv_files/simulated_boundary_f2c_1.csv

GracefulControllerROS:
  max_vel_x: 1.0
  min_vel_x: 0.25

  max_vel_theta: 2.5
  min_vel_theta: 0.3
  min_in_place_vel_theta: 0.6

  acc_lim_x: 0.5
  acc_lim_theta: 1.0

  max_lookahead: 0.75
  initial_rotate_tolerance: 0.25

  odom_topic: odometry/filtered
  
  min_lookahead: 0.3
  prefer_final_rotation: true
